global:
  domain: ttest.supplant.me

configs:
  params:
    server.insecure: true

server:
  service:
    annotations:
      cloud.google.com/neg: '{"ingress": true}'
      cloud.google.com/backend-config: '{"ports": {"http":"argocd-server"}}'
      

  ingress:
    enabled: true
    controller: gke
    host: argocd.ttest.supplant.me
    gke:
      backendConfig:
        healthCheck:
          checkIntervalSec: 30
          timeoutSec: 5
          healthyThreshold: 1
          unhealthyThreshold: 2
          type: HTTP
          requestPath: /healthz
          port: 8080
      frontendConfig:
        redirectToHttps:
          enabled: false 
      managedCertificate:
        create: false

# nginx:
#   service:
#     name: backendconfig-nginx # Unique name for the NGINX service
#     port: 80  # Assuming NGINX serves on port 80
#   ingress:
#     enabled: true
#     host: nginx.ttest.supplant.me  # Define a subdomain for NGINX
#     path: /
#     annotations:
#       cloud.google.com/neg: '{"ingress": true}'  # Enable GCP Network Endpoint Group (NEG) for NGINX
#       cloud.google.com/backend-config: '{"ports": {"http":"backendconfig-nginx"}}'  # Define backend configuration