apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http":"backendconfig-nginx"}}'
spec:
  rules:
    - host: "web.ttest.supplant.me"  # Add your domain here
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-nginx  # Your NGINX service name
                port:
                  number: 80  # Port your service is exposing