# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx-ingress
#   namespace: {{ .Values.namespace }}
# spec:
#   defaultBackend:
#     service:
#       name: service-nginx # Name of the Service targeted by the Ingress
#       port:
#         number: 80 # Should match the port used by the Service