apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  annotations: 
    cloud.google.com/neg: '{"ingress": true, "exposed_ports": {"80": {"name": "nginx-test-gke"}}}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ .Release.Name }}-nginx

