apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: {{ .Values.namespace }}
  annotations: 
    cloud.google.com/neg: '{"ingress": true}'
    #cloud.google.com/neg: '{"exposed_ports": {"80": {"name": "nginx-test-gke"}}}'
    cloud.google.com/backend-config: '{"ports": {"http":"backendconfig-nginx"}}'
    # # cloud.google.com/neg: '{"exposed_ports": {"80": {"name": "nginx-test-gke"}}}'
    # cloud.google.com/backend-config: '{"ports": {"http":"backendconfig-nginx"}}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ .Release.Name }}

