apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  annotations: 
    cloud.google.com/neg: '{"exposed_ports": {"80": {"name": "nginx-test-gke"}}}'
    cloud.google.com/backend-config: '{"default": "backendconfig-nginx"}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ .Release.Name }}-nginx

